In [1]:
import numpy as np # for numerical operations
import pandas as pd # for handling input data
import matplotlib.pyplot as plt # for data visualization 
train = pd.read_csv('BMI_Dataset_train.csv') # uses pandas library to open a .csv file
test = pd.read_csv('BMI_Dataset_test.csv')


In [2]:
x=train.drop(['ID','BMI'],axis=1)
label=train['BMI']

In [3]:
x=np.array(x)
x.shape

(1000, 2)

In [4]:
y=np.array(label)
y=y.reshape((1000,1))
y.shape

(1000, 1)

In [5]:
b=np.ones((1000,1)) #  intercept b0
b.shape

(1000, 1)

In [6]:
x=np.append(b,x,axis=1)

In [7]:
def normal_equation(x,y):
    theta=np.dot(np.linalg.inv(x.T.dot(x)),x.T.dot(y))
    return theta

In [8]:
theta= normal_equation(x,y)
theta.shape

(3, 1)

In [9]:
b=theta[0]
w1=theta[1]
w2=theta[2]
print('b :',b)
print('w1 :',w1)
print('w2 :',w2)

b : [38.70302554]
w1 : [-22.4360351]
w2 : [0.33598111]


In [10]:
test.columns

Index(['ID', 'Height(meter)', 'Weight(KG)'], dtype='object')

In [11]:
x_test=np.array(test.drop(['ID'],axis=1))
x_test.shape

(1000, 2)

In [12]:
bt=np.ones((x_test.shape[0],1))
bt.shape
x_test=np.append(bt,x_test,axis=1)
print(x_test)

[[ 1.          1.7713038  59.24210882]
 [ 1.          1.74540139 59.73260576]
 [ 1.          1.622663   49.25521729]
 ...
 [ 1.          1.75280625 56.90249824]
 [ 1.          1.74484335 59.01481863]
 [ 1.          1.740884   55.90263908]]


In [13]:
ytest=x_test.dot(theta)

In [14]:
ytest

array([[18.86622067],
       [19.6121658 ],
       [18.845724  ],
       [17.17472333],
       [20.33273212],
       [19.11559908],
       [21.97628681],
       [19.62918632],
       [18.02502357],
       [18.65550065],
       [17.92514288],
       [18.49837605],
       [17.18380064],
       [18.68412474],
       [19.61964765],
       [19.41244567],
       [17.33512752],
       [20.14813085],
       [18.79711182],
       [15.75963338],
       [18.25773909],
       [20.76654948],
       [22.05880711],
       [19.01370959],
       [19.56304754],
       [19.29745294],
       [18.57982747],
       [19.39451578],
       [20.65284076],
       [17.83786204],
       [20.93335702],
       [20.26965673],
       [16.84940561],
       [17.98395378],
       [18.60247394],
       [21.39609461],
       [17.73766437],
       [18.01265536],
       [19.04493605],
       [18.09986293],
       [20.28154524],
       [19.17430675],
       [22.93388124],
       [20.07183509],
       [21.09571364],
       [19

In [15]:
"""e = pd.DataFrame({'Id':id_s, 'BMI':ytest})
e.to_csv('no.csv' , encoding = 'utf-8' , index = False)"""

"e = pd.DataFrame({'Id':id_s, 'BMI':y_predicted})\ne.to_csv('no.csv' , encoding = 'utf-8' , index = False)"